name: efsd
channels:
  - defaults
dependencies:
  - pip
  - python==3.11
  - pip:
    - absl-py==2.0.0
    - accelerate==0.23.0
    - aiohttp==3.8.6
    - aiosignal==1.3.1
    - appdirs==1.4.4
    - async-timeout==4.0.3
    - attrs==23.1.0
    - bitsandbytes==0.41.1
    - cachetools==5.3.1
    - certifi==2023.7.22
    - charset-normalizer==3.3.0
    - click==8.1.7
    - cmake==3.27.6
    - datasets==2.14.5
    - dill==0.3.7
    - docker-pycreds==0.4.0
    - filelock==3.12.4
    - frozenlist==1.4.0
    - fsspec==2023.6.0
    - ftfy==6.1.1
    - gitdb==4.0.10
    - gitpython==3.1.37
    - google-auth==2.23.3
    - google-auth-oauthlib==1.0.0
    - grpcio==1.59.0
    - h11==0.14.0
    - huggingface-hub==0.17.3
    - idna==3.4
    - jinja2==3.1.2
    - lit==17.0.2
    - markdown==3.5
    - markupsafe==2.1.3
    - mpmath==1.3.0
    - multidict==6.0.4
    - multiprocess==0.70.15
    - networkx==3.1
    - numpy==1.26.0
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu11==11.7.101
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu11==8.5.0.96
    - nvidia-cudnn-cu12==8.9.2.26
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu11==10.2.10.91
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu11==11.4.0.1
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu11==11.7.4.91
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-nccl-cu11==2.14.3
    - nvidia-nccl-cu12==2.18.1
    - nvidia-nvjitlink-cu12==12.2.140
    - nvidia-nvtx-cu11==11.7.91
    - nvidia-nvtx-cu12==12.1.105
    - oauthlib==3.2.2
    - outcome==1.2.0
    - pandas==2.1.1
    - pathtools==0.1.2
    - pillow==10.0.1
    - protobuf==4.24.4
    - pyarrow==13.0.0
    - pyasn1==0.5.0
    - pyasn1-modules==0.3.0
    - pysocks==1.7.1
    - python-dotenv==1.0.0
    - pytz==2023.3.post1
    - pyyaml==6.0.1
    - regex==2023.10.3
    - requests==2.31.0
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - safetensors==0.4.0
    - scipy==1.11.3
    - selenium==4.13.0
    - sentry-sdk==1.31.0
    - setproctitle==1.3.3
    - smmap==5.0.1
    - sniffio==1.3.0
    - sortedcontainers==2.4.0
    - sympy==1.12
    - tensorboard==2.14.1
    - tensorboard-data-server==0.7.1
    - tokenizers==0.14.1
    - torch==2.0.1
    - torchaudio==2.1.0
    - torchvision==0.16.0
    - tqdm==4.66.1
    - transformers==4.34.0
    - trio==0.22.2
    - trio-websocket==0.11.1
    - triton==2.0.0
    - tzdata==2023.3
    - urllib3==2.0.6
    - wandb==0.15.12
    - webdriver-manager==4.0.1
    - werkzeug==3.0.0
    - wsproto==1.2.0
    - xformers==0.0.22
    - xxhash==3.4.1
    - yarl==1.9.2