name: efsd
channels:
  - defaults
dependencies:
  - pip
  - python==3.11
  - pip:
    - accelerate==0.23.0
    - aiohttp==3.8.6
    - aiosignal==1.3.1
    - async-timeout==4.0.3
    - attrs==23.1.0
    - bitsandbytes==0.41.1
    - certifi==2023.7.22
    - charset-normalizer==3.3.0
    - cmake==3.27.6
    - datasets==2.14.5
    - dill==0.3.7
    - filelock==3.12.4
    - frozenlist==1.4.0
    - fsspec==2023.6.0
    - h11==0.14.0
    - huggingface-hub==0.17.3
    - idna==3.4
    - jinja2==3.1.2
    - lit==17.0.2
    - markupsafe==2.1.3
    - mpmath==1.3.0
    - multidict==6.0.4
    - multiprocess==0.70.15
    - networkx==3.1
    - numpy==1.26.0
    - outcome==1.2.0
    - packaging==23.2
    - pandas==2.1.1
    - psutil==5.9.5
    - pyarrow==13.0.0
    - pysocks==1.7.1
    - python-dateutil==2.8.2
    - python-dotenv==1.0.0
    - pytz==2023.3.post1
    - pyyaml==6.0.1
    - regex==2023.10.3
    - requests==2.31.0
    - safetensors==0.4.0
    - scipy==1.11.3
    - selenium==4.14.0
    - six==1.16.0
    - sniffio==1.3.0
    - sortedcontainers==2.4.0
    - sympy==1.12
    - tokenizers==0.14.1
    - torch==2.0.1
    - torchvision==0.15.2
    - tqdm==4.66.1
    - transformers==4.34.0
    - trio==0.22.2
    - trio-websocket==0.11.1
    - triton==2.0.0
    - typing-extensions==4.8.0
    - tzdata==2023.3
    - urllib3==2.0.6
    - wandb==0.15.12
    - webdriver-manager==4.0.1
    - wsproto==1.2.0
    - xformers==0.0.22
    - xxhash==3.4.1
    - yarl==1.9.2