name: efsd
channels:
  - defaults
dependencies:
  - pip
  - python
  - pip:
      - attrs==23.1.0
      - certifi==2023.7.22
      - charset-normalizer==3.3.0
      - diffusers==0.21.4
      - filelock==3.12.4
      - fsspec==2023.9.2
      - h11==0.14.0
      - huggingface-hub==0.17.3
      - idna==3.4
      - importlib-metadata==6.8.0
      - numpy==1.26.0
      - outcome==1.2.0
      - packaging==23.2
      - pillow==10.0.1
      - pysocks==1.7.1
      - python-dotenv==1.0.0
      - pyyaml==6.0.1
      - regex==2023.10.3
      - requests==2.31.0
      - safetensors==0.4.0
      - selenium==4.13.0
      - sniffio==1.3.0
      - sortedcontainers==2.4.0
      - tokenizers==0.14.1
      - tqdm==4.66.1
      - transformers==4.34.0
      - trio==0.22.2
      - trio-websocket==0.11.1
      - typing-extensions==4.8.0
      - urllib3==2.0.6
      - webdriver-manager==4.0.1
      - wsproto==1.2.0
      - zipp==3.17.0